---
- hosts: all
  tasks:
  - name: i want to install server on ubuntu
    apt:
      name: apache2
      state: present
      when: ansible_os_family =="Debian"

  - name: i want to install  server on Redhat
    yum:
      name: httpd
      state: present
      when:  ansible_os_family =="redhat"
